### ISSUE TITLE
Please push 2.3.0 to Maven Central

### ISSUE THREAD

**Issue by phax** [javaee/jaxb-v2#1133]
The current release can currently only be found at https://maven.java.net/content/repositories/promoted/

Thanks!

**Comment by redwolf2** [comment]
You can get it from here: https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api

**Comment by phax** [comment]
But only the "pre-release" version 2.3.0-b170201.1204
This is just the mirror of http://repo2.maven.org/maven2/javax/xml/bind/jaxb-api/

I want the "2.3.0" release as in https://maven.java.net/content/repositories/promoted/javax/xml/bind/jaxb-api/2.3.0/

**Comment by phax** [comment]
It is on Maven central now.
