### ISSUE TITLE
Where does I could find reference document?

### ISSUE THREAD

**Issue by pollyduan** [javaee/jaxb-v2#1138]
Now, view http://jaxb.java.net,my browser will  redirect to this page.

Where was the JAXB reference ？thks.

**Comment by phax** [comment]
You potentially need to checkout this project, and run `mvn install` on https://github.com/javaee/jaxb-v2/tree/master/jaxb-ri/docs/release-documentation ??

**Comment by bravehorsie** [comment]
Release documentation can be found here
https://javaee.github.io/jaxb-v2/doc/user-guide/

**Comment by pollyduan** [comment]
Thanks bro.
